### ISSUE TITLE
cache queries

### ISSUE THREAD

**Issue by calvinmetcalf** [pouchdb/mapreduce#12]
currently all non-http queries are done from scratch each time, we could save the result from the map query to a _local document and the sequence number, subsequent queries to avoid having to iterate through the whole database, we could even listen to the changes feed and update cache every time a document is created/updated.

**Comment by Rajdev22** [comment]
I have put the decryption to using transform pouch . But my db is locked in IOS safari. i am using safari 10.3.2 version. But i am getting unknown error ( 5 database is locked).
