### ISSUE TITLE
Debug taskqueue recovery

### ISSUE THREAD

**Issue by neojski** [pouchdb/mapreduce#126]
Have a look at [this line](https://github.com/pouchdb/mapreduce/blob/ba534065fc54d901a65f81c6081d8f2325b08063/taskqueue.js#L13) recovering from taskqueue failure. We're implicitly catching errors here which is sooo bad. What's more if you replace it with `console.log` then you'll get:

```
{ [invalid_value: builtin _sum function requires map values to be numbers or number arrays] name: 'invalid_value', status: 500 }
[TypeError: Object.keys called on non-object]
```

This is bad, should not happen.

**Comment by nolanlawson** [comment]
pouchdb-mapreduce has been moved back to core, closing old issues
