### ISSUE TITLE
Review todo comment after pouchdb/pouchdb#1521 solved

### ISSUE THREAD

**Issue by neojski** [pouchdb/mapreduce#135]
https://github.com/pouchdb/pouchdb/issues/1521 got resolved so review https://github.com/pouchdb/mapreduce/blob/b362637ec7167731eed49bbfabce0358029c14c1/index.js#L329

Probably https://github.com/pouchdb/mapreduce/commit/4beaf988873270983a187b3e4f55d776715fcdfe#diff-168726dbe96b3ce427e7fedce31bb0bc commit just outdated that comment.

**Comment by nolanlawson** [comment]
long fixed AFAICT
