### ISSUE TITLE
Simultaneous queries for same view causes slowdown

### ISSUE THREAD

**Issue by psierks** [pouchdb/mapreduce#217]
It seems multiple simultaneous queries for the same view causes a noticeable slowdown.

Test case: https://gist.github.com/anonymous/cd6ca12e95baa6e564b4

It should probably "sequentialize" on a per-view basis

**Comment by marten-de-vries** [comment]
Closing in favour of https://github.com/pouchdb/mapreduce/issues/240 which seems to be a duplicate.
