### ISSUE TITLE
Test PouchDB Server in travis

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/mapreduce#247]
So it was recently revealed (https://github.com/pouchdb/express-pouchdb/pull/166) that express-pouchdb didn't support `_view_cleanup`, which would have been caught if we were testing it here. So we should test it here.

**Comment by marten-de-vries** [comment]
Agreed.

**Comment by marten-de-vries** [comment]
Started to work on this.

**Comment by nolanlawson** [comment]
a2eb43e90e4228b820e8d71d400409600c7ec4a2
