### ISSUE TITLE
Deprecate repo and move issues?

### ISSUE THREAD

**Issue by nickcolley** [pouchdb/mapreduce#273]
mapreduce is in core now? Can I help out migrating issues to core/ providing a deprecation notice?

**Comment by nolanlawson** [comment]
I don't think we need the noise from moving issues out of here. Map/reduce itself is basically deprecated at this point; I just need to get my butt in gear finishing pouchdb-find.

**Comment by nolanlawson** [comment]
A deprecation notice in the README would be helpful though. :)

**Comment by nickcolley** [comment]
@nolanlawson do you still think the notice is the right idea now?

**Comment by nolanlawson** [comment]
Yep! :)

**Comment by nolanlawson** [comment]
I have no idea why I didn't take your advice @nickcolley . The issues definitely need to be moved. Moving them now 😛
