### ISSUE TITLE
Return error if using multi-key fetch and group=false

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/mapreduce#71]
Another weird edge case.  CouchDB returns this error if you use `keys` with >1 key and `group=false`:

``` javascript
{
  "status":400,
  "name":"query_parse_error",
  "message":"Multi-key fetchs for reduce views must use `group=true`"
}
```

**Comment by gooodguy** [comment]
I ran into this error. Additionally, you can't use group=true with include_docs=true.
How can I workaround this error?

**Comment by nolanlawson** [comment]
This issue was moved to pouchdb/pouchdb#6294
